# Run Lint and Test cases
name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Check Kotlin lint
        run: ./gradlew ktlintCheck
      - name: Run tests
        run: ./gradlew testDebugUnitTest
