# Run Lint and Test cases
name: Web CI

on:
  pull_request:
    branches: [ master ]

jobs:
  # CI
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 26.3.0
      - name: Check Kotlin lint
        run: ./gradlew ktlintCheck
      - name: Run tests
        run: ./gradlew testDebugUnitTest testAndroidHostTest
