# Run Lint and Test cases
name: Web CI

on:
  pull_request:
    branches: [ master ]

jobs:
  # CI
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check Kotlin lint
        run: ./gradlew ktlintCheck
      - name: Run tests
        run: ./gradlew testDebugUnitTest