# Test and deploy Compose Multiplatform Web
name: Web CI-CD

on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # CI
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 26.3.0
      - name: Check Kotlin lint
        run: ./gradlew ktlintCheck
      - name: Run tests
        run: ./gradlew testDebugUnitTest testAndroidHostTest
  # CD
  deploy:
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 26.3.0
      - name: Build Website
        run: ./gradlew :web-compose:jsBrowserDistribution
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web-compose/build/dist/js/productionExecutable
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
