# Test and deploy KVision Website
name: Web CI-CD

on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # CI
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check Kotlin lint
        run: ./gradlew ktlintCheck
      - name: Run tests
        run: ./gradlew testDebugUnitTest
  # CD
  deploy:
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Website
        run: ./gradlew zip
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './web-kvision/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
